affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cpu
grid: 4
grid_eps: 0.02
grid_range:
- -1
- 1
k: 3
mult_arity: 2
round: 1
sb_trainable: true
sp_trainable: true
state_id: 14
symbolic.funs_name.0:
- - sin
  - x
- - x
  - x
symbolic.funs_name.1:
- - xsinx
  - '0'
symbolic_enabled: false
width:
- - 2
  - 0
- - 2
  - 0
- - 1
  - 0
